WWS-00639q_S33_L001.clipped.bam
Traceback (most recent call last):
  File "/home/rchap/anaconda3/envs/ivar-freyja/bin/freyja", line 6, in <module>
    from freyja._cli import cli
  File "/home/rchap/anaconda3/envs/ivar-freyja/lib/python3.10/site-packages/freyja/_cli.py", line 2, in <module>
    import pandas as pd
  File "/home/rchap/anaconda3/envs/ivar-freyja/lib/python3.10/site-packages/pandas/__init__.py", line 11, in <module>
    __import__(dependency)
  File "/home/rchap/anaconda3/envs/ivar-freyja/lib/python3.10/site-packages/numpy/__init__.py", line 144, in <module>
    from . import core
  File "/home/rchap/anaconda3/envs/ivar-freyja/lib/python3.10/site-packages/numpy/core/__init__.py", line 73, in <module>
    from . import numeric
  File "/home/rchap/anaconda3/envs/ivar-freyja/lib/python3.10/site-packages/numpy/core/numeric.py", line 24, in <module>
    from . import shape_base
  File "/home/rchap/anaconda3/envs/ivar-freyja/lib/python3.10/site-packages/numpy/core/shape_base.py", line 12, in <module>
    from . import fromnumeric as _from_nx
  File "/home/rchap/anaconda3/envs/ivar-freyja/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 14, in <module>
    from . import _methods
  File "/home/rchap/anaconda3/envs/ivar-freyja/lib/python3.10/site-packages/numpy/core/_methods.py", line 13, in <module>
    from numpy.core import _exceptions
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1012, in get_code
  File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
KeyboardInterrupt
